version: "2"
services:
  web: 
  image: bgrober/quotes:demo
    ports: 
      - 80:1337
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; npm start'
    depends_on:
      - db
  db:
    image: postgres
    ports:
      - "5432:5432"

